import { StyleProfile } from "../validation/schemas";

export const STYLE_PRESETS: Record<string, StyleProfile> = {
  dark_cinematic: {
    id: "dark_cinematic",
    name: "Dark Cinematic",
    tone: "intense, atmospheric, filmic",
    captionStyle: {
      fontFamily: "'Georgia', serif",
      fontSize: 52,
      color: "#ffffff",
      highlightColor: "#e94560",
      animation: "phrase_slide",
      position: "bottom",
      maxWordsPerGroup: 4,
    },
    motionStyle: "ken_burns",
    transitionStyle: "fade",
    colorStrategy: {
      palette: ["#0a0a0a", "#1a1a2e", "#e94560", "#16213e"],
      overlayOpacity: 0.4,
      vignetteStrength: 0.7,
      tint: null,
    },
    narrationStyle: "dramatic",
    visualMixRules: {
      maxConsecutiveSameMode: 2,
      requiredModeVariation: 3,
      preferredModes: ["stockVideo", "stockImage", "quoteCard"],
    },
    pacingRules: {
      defaultPaddingMs: 800,
      audioPaddingMs: 400,
      minSceneDurationMs: 4000,
      maxSceneDurationMs: 14000,
    },
  },

  documentary: {
    id: "documentary",
    name: "Documentary",
    tone: "measured, factual, authoritative",
    captionStyle: {
      fontFamily: "'Helvetica Neue', sans-serif",
      fontSize: 46,
      color: "#f5f5dc",
      highlightColor: "#4a9eff",
      animation: "karaoke",
      position: "bottom",
      maxWordsPerGroup: 5,
    },
    motionStyle: "drift",
    transitionStyle: "cut",
    colorStrategy: {
      palette: ["#1c1c1c", "#2d4a22", "#f5f5dc", "#8b7355"],
      overlayOpacity: 0.25,
      vignetteStrength: 0.4,
      tint: null,
    },
    narrationStyle: "authoritative",
    visualMixRules: {
      maxConsecutiveSameMode: 2,
      requiredModeVariation: 3,
      preferredModes: ["stockVideo", "evidenceCard", "stockImage"],
    },
    pacingRules: {
      defaultPaddingMs: 600,
      audioPaddingMs: 300,
      minSceneDurationMs: 5000,
      maxSceneDurationMs: 15000,
    },
  },

  internet_mystery: {
    id: "internet_mystery",
    name: "Internet Mystery",
    tone: "conspiratorial, urgent, unsettling",
    captionStyle: {
      fontFamily: "'Courier New', monospace",
      fontSize: 50,
      color: "#00ff41",
      highlightColor: "#ff00ff",
      animation: "word_pop",
      position: "center",
      maxWordsPerGroup: 3,
    },
    motionStyle: "zoom_in",
    transitionStyle: "glitch",
    colorStrategy: {
      palette: ["#000000", "#1a0033", "#ff00ff", "#00ff41"],
      overlayOpacity: 0.5,
      vignetteStrength: 0.85,
      tint: "#0d0020",
    },
    narrationStyle: "conspiratorial",
    visualMixRules: {
      maxConsecutiveSameMode: 2,
      requiredModeVariation: 3,
      preferredModes: ["evidenceCard", "textCard", "stockImage"],
    },
    pacingRules: {
      defaultPaddingMs: 500,
      audioPaddingMs: 200,
      minSceneDurationMs: 3000,
      maxSceneDurationMs: 10000,
    },
  },

  finance_news: {
    id: "finance_news",
    name: "Finance / News",
    tone: "sharp, factual, urgent",
    captionStyle: {
      fontFamily: "'Arial', sans-serif",
      fontSize: 48,
      color: "#ffffff",
      highlightColor: "#f4d03f",
      animation: "typewriter",
      position: "bottom",
      maxWordsPerGroup: 6,
    },
    motionStyle: "static",
    transitionStyle: "wipe",
    colorStrategy: {
      palette: ["#0d1b2a", "#1b4332", "#f4d03f", "#e74c3c"],
      overlayOpacity: 0.3,
      vignetteStrength: 0.3,
      tint: null,
    },
    narrationStyle: "urgent",
    visualMixRules: {
      maxConsecutiveSameMode: 2,
      requiredModeVariation: 3,
      preferredModes: ["evidenceCard", "stockImage", "timelineCard"],
    },
    pacingRules: {
      defaultPaddingMs: 400,
      audioPaddingMs: 200,
      minSceneDurationMs: 4000,
      maxSceneDurationMs: 12000,
    },
  },

  horror_story: {
    id: "horror_story",
    name: "Horror Story",
    tone: "dread, slow burn, disturbing",
    captionStyle: {
      fontFamily: "'Georgia', serif",
      fontSize: 54,
      color: "#cc0000",
      highlightColor: "#ff4444",
      animation: "phrase_slide",
      position: "center",
      maxWordsPerGroup: 3,
    },
    motionStyle: "drift",
    transitionStyle: "glitch",
    colorStrategy: {
      palette: ["#0d0000", "#1a0000", "#8b0000", "#2d0000"],
      overlayOpacity: 0.6,
      vignetteStrength: 0.9,
      tint: "#200000",
    },
    narrationStyle: "dramatic",
    visualMixRules: {
      maxConsecutiveSameMode: 2,
      requiredModeVariation: 3,
      preferredModes: ["stockImage", "gradientMotionCard", "quoteCard"],
    },
    pacingRules: {
      defaultPaddingMs: 1200,
      audioPaddingMs: 600,
      minSceneDurationMs: 5000,
      maxSceneDurationMs: 16000,
    },
  },

  motivational: {
    id: "motivational",
    name: "Motivational",
    tone: "energetic, empowering, bold",
    captionStyle: {
      fontFamily: "'Impact', 'Arial Black', sans-serif",
      fontSize: 58,
      color: "#ffffff",
      highlightColor: "#ff6b35",
      animation: "word_pop",
      position: "center",
      maxWordsPerGroup: 3,
    },
    motionStyle: "zoom_in",
    transitionStyle: "zoom_through",
    colorStrategy: {
      palette: ["#000000", "#1a1a1a", "#ff6b35", "#ffd700"],
      overlayOpacity: 0.2,
      vignetteStrength: 0.5,
      tint: null,
    },
    narrationStyle: "calm",
    visualMixRules: {
      maxConsecutiveSameMode: 2,
      requiredModeVariation: 3,
      preferredModes: ["stockVideo", "gradientMotionCard", "quoteCard"],
    },
    pacingRules: {
      defaultPaddingMs: 500,
      audioPaddingMs: 300,
      minSceneDurationMs: 3500,
      maxSceneDurationMs: 11000,
    },
  },

  sports_commentary: {
    id: "sports_commentary",
    name: "Sports Commentary",
    tone: "high energy, fast, punchy",
    captionStyle: {
      fontFamily: "'Arial Black', sans-serif",
      fontSize: 56,
      color: "#ffffff",
      highlightColor: "#ffab00",
      animation: "karaoke",
      position: "bottom",
      maxWordsPerGroup: 4,
    },
    motionStyle: "ken_burns",
    transitionStyle: "cut",
    colorStrategy: {
      palette: ["#0a0e27", "#1a237e", "#ffab00", "#e53935"],
      overlayOpacity: 0.25,
      vignetteStrength: 0.4,
      tint: null,
    },
    narrationStyle: "urgent",
    visualMixRules: {
      maxConsecutiveSameMode: 2,
      requiredModeVariation: 3,
      preferredModes: ["stockVideo", "stockImage", "gradientMotionCard"],
    },
    pacingRules: {
      defaultPaddingMs: 300,
      audioPaddingMs: 150,
      minSceneDurationMs: 2500,
      maxSceneDurationMs: 9000,
    },
  },
};
